# Site settings
title: HG Blog
SEOTitle: HG
header-img: img/home-bg-art.jpg
email: 1961154734@qq.com
description: "@HG 的个人博客"
keyword: "HG,Java,SSM,Spring,后端,HG的博客,HG Blog, 博客"
url: "https://www.hglll.top" # your host, for absolute URL
baseurl: "" 
future: true
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: HG

# Netease settings
netease_comment: false

# baidu Analytics
ga_track_id: '045743b5d09fa3bbf0cb5606c19a3e4d'
ga_domain: www.hglll.top

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "年轻是我们唯一拥有权利去编织梦想的时光" 
sidebar-avatar: /img/avatar-wb.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false